# Generated by Django 4.0.1 on 2022-02-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='campo1',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='campo2',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='campo3',
            new_name='usuario',
        ),
    ]
